version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DSN=postgresql://guest:guest@postgres:5432/speakeasy?sslmode=disable # Test credentials
      - SPEAKEASY_ENVIRONMENT=docker
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: speakeasy
    ports:
      - "5432:5432"
